
# POST https://api.openai.com/v1/chat/completions
# Authorization: Bearer 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
# content-type: application/json

# {
#     "model": "gpt-3.5-turbo",
#     "messages": [
#         {
#             "role": "system",
#             "content": "yourself"
#         },
#         {
#             "role": "user",
#             "content": "explain composition api in a course content format, then take each of the course outlines and explain properly in an article format "
#         }
#     ]
# }

# POST https://api.openai.com/v1/chat/completions
# Authorization: Bearer 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
# Content-Type: application/json

# {
#   "model": "gpt-3.5-turbo",
# "max_tokens":3000,  
  # "temperature":0.8,
#   "messages": [
#     {"role": "system", "content": "You are a knowledgeable assistant that provides detailed explanations about topics."},
#     {"role": "user", "content": "Generate 10 array of ten subheadings starting from Introduction and ending with conclusion on the topic composition Api for a course creation targeted at developers return the response in one dimensional array of the format []"}
#   ]
# }

GET https://api3.getresponse360.com/v3/campaigns
# Authorization: Bearer pxck0psjdi8tipukr0w24fh1d9ct3vi6
X-Auth-Token: api-key pxck0psjdi8tipukr0w24fh1d9ct3vi6
Content-Type: application/json



# contact@successwithsteve.info
#  james.milo@gmail.com
# jvaccess@myconvergeai.com

# domain: myconvergeai.com
# ------------------------------
# ssh access:
# host: 66.29.138.34
# port: 21098
# username: tubetargeterapp
# password: TubeT@rget8

# princeken9609


